name: "setup-node"
runs:
  using: "composite"
  permissions:
    id-token: write
    contents: read
  steps:
    - uses: google-github-actions/auth@v1
      with:
        workload_identity_provider: '${{ secrets.GCP_WIF_PROVIDER }}'
        service_account: '${{ secrets.GCP_WIF_SERVICE_ACCOUNT }}'
