name: "setup-rust"
runs:
  using: "composite"
  steps:
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
          target_check
        key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.lock') }}
    - run: rustup override set 1.80.0
      shell: bash
    - run: rustup component add rustfmt clippy
      shell: bash
    - run: sudo apt-get update && sudo apt-get install -y libvips-dev
      shell: bash
