gcp_project                    = "taishi-wtf"
gcp_artifact_registry_location = "asia-northeast1"
gcp_cloud_run_location         = "asia-northeast1"
cf_pages_domain                = "taishi.wtf"
cf_pages_repo_owner            = "taishinaritomi"
cf_pages_repo_name             = "taishi.wtf"
cf_account_id                  = "9773bf794cd89a557f32f6fa904fdec9"
